import { NextApiRequest, NextApiResponse } from 'next';

const products = [
    {
      id: 1,
      name: "Acer Aspire 5",
      category: "Laptop",
      brand: "Acer",
      price: 14500000,
      oldPrice: 15990000,
      discount: 9,
      available: 8,
      quantity: 40,
      cpu: "Intel Core i5-1235U",
      ram: "8GB",
      storage: "512GB SSD",
      screen: "15.6 inch, Full HD",
      gpu: "Intel Iris Xe Graphics",
      battery: "48Wh",
      os: "Windows 11",
      description: "Laptop phổ thông với hiệu năng ổn định, phù hợp cho học tập và văn phòng.",
      image: "/images/laptop.jpeg"
    },
    {
      id: 2,
      name: "Dell XPS 13",
      category: "Laptop",
      brand: "Dell",
      price: 31990000,
      oldPrice: 34990000,
      discount: 9,
      available: 8,
      quantity: 40,
      cpu: "Intel Core i7-1360P",
      ram: "16GB",
      storage: "1TB SSD",
      screen: "13.4 inch, 3.5K OLED",
      gpu: "Intel Iris Xe Graphics",
      battery: "52Wh",
      os: "Windows 11",
      description: "Ultrabook cao cấp với màn hình tuyệt đẹp và hiệu năng mạnh mẽ.",
      image: "/images/laptop.jpeg"
    },
    {
      id: 3,
      name: "HP Spectre x360",
      category: "Laptop",
      brand: "HP",
      price: 33990000,
      oldPrice: 37990000,
      discount: 11,
      available: 8,
      quantity: 40,
      cpu: "Intel Core i7-1355U",
      ram: "16GB",
      storage: "1TB SSD",
      screen: "13.5 inch, 3K2K OLED",
      gpu: "Intel Iris Xe Graphics",
      battery: "66Wh",
      os: "Windows 11",
      description: "Laptop 2-in-1 linh hoạt, thiết kế sang trọng với màn hình cảm ứng sắc nét.",
      image: "/images/laptop.jpeg"
    },
    {
      id: 4,
      name: "MacBook Air M2",
      category: "Laptop",
      brand: "Apple",
      price: 28990000,
      oldPrice: 31990000,
      discount: 9,
      available: 8,
      quantity: 40,
      cpu: "Apple M2",
      ram: "8GB",
      storage: "256GB SSD",
      screen: "13.6 inch, Retina",
      gpu: "Apple GPU 8-core",
      battery: "52.6Wh",
      os: "macOS",
      description: "Laptop mỏng nhẹ với chip M2 mạnh mẽ và thời lượng pin xuất sắc.",
      image: "/images/laptop.jpeg"
    },
    {
      id: 5,
      name: "Lenovo ThinkPad X1 Carbon",
      category: "Laptop",
      brand: "Lenovo",
      price: 35990000,
      oldPrice: 39990000,
      discount: 10,
      available: 8,
      quantity: 40,
      cpu: "Intel Core i7-1360P",
      ram: "16GB",
      storage: "512GB SSD",
      screen: "14 inch, WUXGA",
      gpu: "Intel Iris Xe Graphics",
      battery: "57Wh",
      os: "Windows 11",
      description: "Laptop doanh nhân với độ bền cao và bàn phím tiện dụng.",
      image: "/images/laptop.jpeg"
    },
    {
        id: 6,
        name: "Acer Aspire 5",
        category: "Laptop",
        brand: "Acer",
        price: 14500000,
        oldPrice: 15990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: "Intel Core i5-1235U",
        ram: "8GB",
        storage: "512GB SSD",
        screen: "15.6 inch, Full HD",
        gpu: "Intel Iris Xe Graphics",
        battery: "48Wh",
        os: "Windows 11",
        description: "Laptop phổ thông với hiệu năng ổn định, phù hợp cho học tập và văn phòng.",
        image: "/images/laptop.jpeg"
      },
      {
        id: 7,
        name: "Dell XPS 13",
        category: "Laptop",
        brand: "Dell",
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: "Intel Core i7-1360P",
        ram: "16GB",
        storage: "1TB SSD",
        screen: "13.4 inch, 3.5K OLED",
        gpu: "Intel Iris Xe Graphics",
        battery: "52Wh",
        os: "Windows 11",
        description: "Ultrabook cao cấp với màn hình tuyệt đẹp và hiệu năng mạnh mẽ.",
        image: "/images/laptop.jpeg"
      },
      {
        id: 8,
        name: "HP Spectre x360",
        category: "Laptop",
        brand: "HP",
        price: 33990000,
        oldPrice: 37990000,
        discount: 11,
        available: 8,
        quantity: 40,
        cpu: "Intel Core i7-1355U",
        ram: "16GB",
        storage: "1TB SSD",
        screen: "13.5 inch, 3K2K OLED",
        gpu: "Intel Iris Xe Graphics",
        battery: "66Wh",
        os: "Windows 11",
        description: "Laptop 2-in-1 linh hoạt, thiết kế sang trọng với màn hình cảm ứng sắc nét.",
        image: "/images/laptop.jpeg"
      },
      {
        id: 9,
        name: "MacBook Air M2",
        category: "Laptop",
        brand: "Apple",
        price: 28990000,
        oldPrice: 31990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: "Apple M2",
        ram: "8GB",
        storage: "256GB SSD",
        screen: "13.6 inch, Retina",
        gpu: "Apple GPU 8-core",
        battery: "52.6Wh",
        os: "macOS",
        description: "Laptop mỏng nhẹ với chip M2 mạnh mẽ và thời lượng pin xuất sắc.",
        image: "/images/laptop.jpeg"
      },
      {
        id: 10,
        name: "Lenovo ThinkPad X1 Carbon",
        category: "Laptop",
        brand: "Lenovo",
        price: 35990000,
        oldPrice: 39990000,
        discount: 10,
        available: 8,
        quantity: 40,
        cpu: "Intel Core i7-1360P",
        ram: "16GB",
        storage: "512GB SSD",
        screen: "14 inch, WUXGA",
        gpu: "Intel Iris Xe Graphics",
        battery: "57Wh",
        os: "Windows 11",
        description: "Laptop doanh nhân với độ bền cao và bàn phím tiện dụng.",
        image: "/images/laptop.jpeg"
      }
];

export async function GET(req: Request) {
    return new Response(JSON.stringify(products), { status: 200 });
}