// import { NextApiRequest, NextApiResponse } from 'next';

const products = [
    {
        id: 1,
        name: 'Acer Aspire 5',
        category: 'Laptop',
        brand: 'Acer',
        price: 14500000,
        oldPrice: 15990000,
        discount: 9,
        available: 9,
        quantity: 40,
        cpu: 'Intel Core i5-1235U',
        ram: '8GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD',
        gpu: 'Intel Iris Xe Graphics',
        battery: '48Wh',
        os: 'Windows 11',
        description: 'Laptop phổ thông với hiệu năng ổn định, phù hợp cho học tập và văn phòng.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 2,
        name: 'Dell XPS 13',
        category: 'Laptop',
        brand: 'Dell',
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: 'Intel Core i7-1360P',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '13.4 inch, 3.5K OLED',
        gpu: 'Intel Iris Xe Graphics',
        battery: '52Wh',
        os: 'Windows 11',
        description: 'Ultrabook cao cấp với màn hình tuyệt đẹp và hiệu năng mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 3,
        name: 'HP Spectre x360',
        category: 'Laptop',
        brand: 'HP',
        price: 33990000,
        oldPrice: 37990000,
        discount: 11,
        available: 12,
        quantity: 40,
        cpu: 'Intel Core i7-1355U',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '13.5 inch, 3K2K OLED',
        gpu: 'Intel Iris Xe Graphics',
        battery: '66Wh',
        os: 'Windows 11',
        description: 'Laptop 2-in-1 linh hoạt, thiết kế sang trọng với màn hình cảm ứng sắc nét.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 4,
        name: 'MacBook Air M2',
        category: 'Laptop',
        brand: 'Apple',
        price: 28990000,
        oldPrice: 31990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: 'Apple M2',
        ram: '8GB',
        storage: '256GB SSD',
        screen: '13.6 inch, Retina',
        gpu: 'Apple GPU 8-core',
        battery: '52.6Wh',
        os: 'macOS',
        description: 'Laptop mỏng nhẹ với chip M2 mạnh mẽ và thời lượng pin xuất sắc.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 5,
        name: 'Lenovo ThinkPad X1 Carbon',
        category: 'Laptop',
        brand: 'Lenovo',
        price: 35990000,
        oldPrice: 39990000,
        discount: 10,
        available: 8,
        quantity: 40,
        cpu: 'Intel Core i7-1360P',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '14 inch, WUXGA',
        gpu: 'Intel Iris Xe Graphics',
        battery: '57Wh',
        os: 'Windows 11',
        description: 'Laptop doanh nhân với độ bền cao và bàn phím tiện dụng.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 6,
        name: 'Asus ROG Zephyrus G14',
        category: 'Laptop',
        brand: 'Asus',
        price: 42990000,
        oldPrice: 46990000,
        discount: 9,
        available: 10,
        quantity: 40,
        cpu: 'AMD Ryzen 9 6900HS',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '14 inch, WQXGA 120Hz',
        gpu: 'AMD Radeon RX 6800S',
        battery: '76Wh',
        os: 'Windows 11',
        description: 'Laptop gaming mỏng nhẹ với hiệu năng mạnh mẽ và màn hình 120Hz.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 7,
        name: 'MSI Katana GF66',
        category: 'Laptop',
        brand: 'MSI',
        price: 25990000,
        oldPrice: 28990000,
        discount: 10,
        available: 12,
        quantity: 40,
        cpu: 'Intel Core i7-12650H',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD 144Hz',
        gpu: 'NVIDIA GeForce RTX 3060',
        battery: '53.5Wh',
        os: 'Windows 11',
        description: 'Laptop gaming phổ thông với card đồ họa RTX 3060 mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 8,
        name: 'Gigabyte AERO 16',
        category: 'Laptop',
        brand: 'Gigabyte',
        price: 48990000,
        oldPrice: 52990000,
        discount: 8,
        available: 7,
        quantity: 40,
        cpu: 'Intel Core i9-13900H',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '16 inch, 4K OLED',
        gpu: 'NVIDIA GeForce RTX 4070',
        battery: '99Wh',
        os: 'Windows 11',
        description: 'Laptop dành cho đồ họa và sáng tạo nội dung với màn hình OLED 4K.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 9,
        name: 'Razer Blade 15',
        category: 'Laptop',
        brand: 'Razer',
        price: 52990000,
        oldPrice: 56990000,
        discount: 7,
        available: 6,
        quantity: 40,
        cpu: 'Intel Core i7-13800H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '15.6 inch, QHD 240Hz',
        gpu: 'NVIDIA GeForce RTX 4070',
        battery: '80Wh',
        os: 'Windows 11',
        description: 'Laptop gaming cao cấp với màn hình 240Hz cực mượt.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 10,
        name: 'Samsung Galaxy Book3 Ultra',
        category: 'Laptop',
        brand: 'Samsung',
        price: 48990000,
        oldPrice: 51990000,
        discount: 6,
        available: 5,
        quantity: 40,
        cpu: 'Intel Core i9-13900H',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '16 inch, 3K AMOLED',
        gpu: 'NVIDIA GeForce RTX 4050',
        battery: '76Wh',
        os: 'Windows 11',
        description: 'Ultrabook cao cấp với màn hình AMOLED và hiệu năng mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 11,
        name: 'Acer Nitro 5',
        category: 'Laptop',
        brand: 'Acer',
        price: 22990000,
        oldPrice: 25990000,
        discount: 12,
        available: 15,
        quantity: 40,
        cpu: 'Intel Core i5-12500H',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD 144Hz',
        gpu: 'NVIDIA GeForce RTX 3050',
        battery: '57.5Wh',
        os: 'Windows 11',
        description: 'Laptop gaming phổ thông với hiệu năng mạnh mẽ và tản nhiệt tốt.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 12,
        name: 'Dell Inspiron 16 Plus',
        category: 'Laptop',
        brand: 'Dell',
        price: 27990000,
        oldPrice: 30990000,
        discount: 10,
        available: 10,
        quantity: 40,
        cpu: 'Intel Core i7-12700H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '16 inch, 3K IPS',
        gpu: 'Intel Iris Xe Graphics',
        battery: '86Wh',
        os: 'Windows 11',
        description: 'Laptop đồ họa với màn hình lớn và hiệu năng mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 13,
        name: 'HP Envy x360 15',
        category: 'Laptop',
        brand: 'HP',
        price: 24990000,
        oldPrice: 27990000,
        discount: 11,
        available: 12,
        quantity: 40,
        cpu: 'AMD Ryzen 7 5700U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD Touch',
        gpu: 'AMD Radeon Graphics',
        battery: '51Wh',
        os: 'Windows 11',
        description: 'Laptop 2-in-1 linh hoạt với màn hình cảm ứng và hiệu năng ổn định.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 14,
        name: 'Apple MacBook Pro 14 M3',
        category: 'Laptop',
        brand: 'Apple',
        price: 45990000,
        oldPrice: 49990000,
        discount: 8,
        available: 8,
        quantity: 40,
        cpu: 'Apple M3 Pro',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '14.2 inch, Liquid Retina XDR',
        gpu: 'Apple GPU 14-core',
        battery: '70Wh',
        os: 'macOS',
        description: 'MacBook Pro mạnh mẽ với chip M3 Pro và màn hình XDR sắc nét.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 15,
        name: 'Microsoft Surface Laptop 5',
        category: 'Laptop',
        brand: 'Microsoft',
        price: 29990000,
        oldPrice: 32990000,
        discount: 9,
        available: 9,
        quantity: 40,
        cpu: 'Intel Core i7-1265U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '13.5 inch, PixelSense',
        gpu: 'Intel Iris Xe Graphics',
        battery: '47.4Wh',
        os: 'Windows 11',
        description: 'Laptop siêu nhẹ với thiết kế tinh tế và màn hình cảm ứng PixelSense.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 16,
        name: 'Asus ZenBook 14 OLED',
        category: 'Laptop',
        brand: 'Asus',
        price: 23990000,
        oldPrice: 26990000,
        discount: 11,
        available: 10,
        quantity: 40,
        cpu: 'AMD Ryzen 7 6800U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '14 inch, 2.8K OLED',
        gpu: 'AMD Radeon Graphics',
        battery: '75Wh',
        os: 'Windows 11',
        description: 'Ultrabook nhỏ gọn với màn hình OLED sắc nét và hiệu năng cao.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 17,
        name: 'Lenovo Legion 5 Pro',
        category: 'Laptop',
        brand: 'Lenovo',
        price: 34990000,
        oldPrice: 38990000,
        discount: 10,
        available: 12,
        quantity: 40,
        cpu: 'AMD Ryzen 7 6800H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '16 inch, WQXGA 165Hz',
        gpu: 'NVIDIA GeForce RTX 3070 Ti',
        battery: '80Wh',
        os: 'Windows 11',
        description: 'Laptop gaming với màn hình lớn, tần số quét cao và hiệu năng mạnh.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 18,
        name: 'Gigabyte G5 KE',
        category: 'Laptop',
        brand: 'Gigabyte',
        price: 25990000,
        oldPrice: 28990000,
        discount: 10,
        available: 14,
        quantity: 40,
        cpu: 'Intel Core i5-12500H',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD 144Hz',
        gpu: 'NVIDIA GeForce RTX 3060',
        battery: '49Wh',
        os: 'Windows 11',
        description: 'Laptop gaming giá tốt với card đồ họa RTX 3060 và màn hình 144Hz.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 19,
        name: 'Samsung Galaxy Book2 Pro 360',
        category: 'Laptop',
        brand: 'Samsung',
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 8,
        quantity: 40,
        cpu: 'Intel Core i7-1260P',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD AMOLED Touch',
        gpu: 'Intel Iris Xe Graphics',
        battery: '68Wh',
        os: 'Windows 11',
        description: 'Laptop 2-in-1 với màn hình AMOLED cảm ứng và thiết kế mỏng nhẹ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 20,
        name: 'Razer Blade 16',
        category: 'Laptop',
        brand: 'Razer',
        price: 68990000,
        oldPrice: 72990000,
        discount: 6,
        available: 5,
        quantity: 40,
        cpu: 'Intel Core i9-13950HX',
        ram: '32GB',
        storage: '2TB SSD',
        screen: '16 inch, Dual Mode Mini-LED 4K/240Hz',
        gpu: 'NVIDIA GeForce RTX 4090',
        battery: '95Wh',
        os: 'Windows 11',
        description: 'Laptop gaming cao cấp với GPU RTX 4090 và màn hình Mini-LED độc đáo.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 21,
        name: 'Asus TUF Gaming F15',
        category: 'Laptop',
        brand: 'Asus',
        price: 25990000,
        oldPrice: 28990000,
        discount: 10,
        available: 14,
        quantity: 40,
        cpu: 'Intel Core i7-12700H',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD 144Hz',
        gpu: 'NVIDIA GeForce RTX 3060',
        battery: '90Wh',
        os: 'Windows 11',
        description: 'Laptop gaming bền bỉ với tản nhiệt tốt và hiệu năng mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 22,
        name: 'Dell Latitude 7430',
        category: 'Laptop',
        brand: 'Dell',
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 10,
        quantity: 40,
        cpu: 'Intel Core i7-1265U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '14 inch, Full HD',
        gpu: 'Intel Iris Xe Graphics',
        battery: '58Wh',
        os: 'Windows 11',
        description: 'Laptop doanh nhân cao cấp với thiết kế bền bỉ và hiệu năng ổn định.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 23,
        name: 'HP Pavilion Aero 13',
        category: 'Laptop',
        brand: 'HP',
        price: 19990000,
        oldPrice: 22990000,
        discount: 13,
        available: 12,
        quantity: 40,
        cpu: 'AMD Ryzen 7 5800U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '13.3 inch, WUXGA',
        gpu: 'AMD Radeon Graphics',
        battery: '43Wh',
        os: 'Windows 11',
        description: 'Laptop siêu nhẹ với hiệu năng tốt cho học tập và làm việc.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 24,
        name: 'Apple MacBook Pro 16 M3 Max',
        category: 'Laptop',
        brand: 'Apple',
        price: 79990000,
        oldPrice: 84990000,
        discount: 6,
        available: 6,
        quantity: 40,
        cpu: 'Apple M3 Max',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '16.2 inch, Liquid Retina XDR',
        gpu: 'Apple GPU 38-core',
        battery: '100Wh',
        os: 'macOS',
        description: 'MacBook Pro mạnh nhất với chip M3 Max và màn hình XDR tuyệt đẹp.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 25,
        name: 'Microsoft Surface Pro 9',
        category: 'Laptop',
        brand: 'Microsoft',
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 9,
        quantity: 40,
        cpu: 'Intel Core i7-1255U',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '13 inch, PixelSense Touch',
        gpu: 'Intel Iris Xe Graphics',
        battery: '47Wh',
        os: 'Windows 11',
        description: 'Tablet 2-in-1 cao cấp với màn hình cảm ứng sắc nét và hiệu năng mạnh mẽ.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 26,
        name: 'Acer Swift X 14',
        category: 'Laptop',
        brand: 'Acer',
        price: 27990000,
        oldPrice: 30990000,
        discount: 10,
        available: 12,
        quantity: 40,
        cpu: 'Intel Core i7-13700H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '14 inch, 2.8K OLED',
        gpu: 'NVIDIA GeForce RTX 4050',
        battery: '76Wh',
        os: 'Windows 11',
        description: 'Laptop đồ họa nhỏ gọn với màn hình OLED và card RTX 4050.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 27,
        name: 'Asus ROG Zephyrus G14',
        category: 'Laptop',
        brand: 'Asus',
        price: 41990000,
        oldPrice: 45990000,
        discount: 9,
        available: 10,
        quantity: 40,
        cpu: 'AMD Ryzen 9 7940HS',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '14 inch, QHD 165Hz',
        gpu: 'NVIDIA GeForce RTX 4070',
        battery: '76Wh',
        os: 'Windows 11',
        description: 'Laptop gaming cao cấp với thiết kế siêu mỏng và hiệu năng mạnh.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 28,
        name: 'Lenovo Yoga 9i',
        category: 'Laptop',
        brand: 'Lenovo',
        price: 34990000,
        oldPrice: 38990000,
        discount: 10,
        available: 11,
        quantity: 40,
        cpu: 'Intel Core i7-1360P',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '14 inch, 4K OLED Touch',
        gpu: 'Intel Iris Xe Graphics',
        battery: '75Wh',
        os: 'Windows 11',
        description: 'Laptop 2-in-1 cao cấp với màn hình OLED 4K và thiết kế tinh tế.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 29,
        name: 'Samsung Galaxy Book3 Ultra',
        category: 'Laptop',
        brand: 'Samsung',
        price: 52990000,
        oldPrice: 56990000,
        discount: 7,
        available: 7,
        quantity: 40,
        cpu: 'Intel Core i9-13900H',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '16 inch, 3K AMOLED',
        gpu: 'NVIDIA GeForce RTX 4070',
        battery: '76Wh',
        os: 'Windows 11',
        description: 'Ultrabook cao cấp với màn hình AMOLED và card đồ họa RTX 4070.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 30,
        name: 'MSI Stealth 15M',
        category: 'Laptop',
        brand: 'MSI',
        price: 31990000,
        oldPrice: 34990000,
        discount: 9,
        available: 9,
        quantity: 40,
        cpu: 'Intel Core i7-13620H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '15.6 inch, Full HD 144Hz',
        gpu: 'NVIDIA GeForce RTX 4060',
        battery: '53Wh',
        os: 'Windows 11',
        description: 'Laptop gaming mỏng nhẹ với card đồ họa RTX 4060 và hiệu năng cao.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 31,
        name: 'LG Gram 16',
        category: 'Laptop',
        brand: 'LG',
        price: 34990000,
        oldPrice: 37990000,
        discount: 8,
        available: 10,
        quantity: 40,
        cpu: 'Intel Core i7-1360P',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '16 inch, WQXGA',
        gpu: 'Intel Iris Xe Graphics',
        battery: '80Wh',
        os: 'Windows 11',
        description: 'Laptop siêu nhẹ với pin lâu và màn hình lớn WQXGA.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 32,
        name: 'Razer Blade 14',
        category: 'Laptop',
        brand: 'Razer',
        price: 49990000,
        oldPrice: 53990000,
        discount: 7,
        available: 7,
        quantity: 40,
        cpu: 'AMD Ryzen 9 7940HS',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '14 inch, QHD 165Hz',
        gpu: 'NVIDIA GeForce RTX 4070',
        battery: '61.6Wh',
        os: 'Windows 11',
        description: 'Laptop gaming nhỏ gọn với hiệu năng mạnh mẽ và màn hình 165Hz.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 33,
        name: 'HP Envy x360 15',
        category: 'Laptop',
        brand: 'HP',
        price: 23990000,
        oldPrice: 26990000,
        discount: 11,
        available: 12,
        quantity: 40,
        cpu: 'Intel Core i7-1260P',
        ram: '16GB',
        storage: '512GB SSD',
        screen: '15.6 inch, Full HD Touch',
        gpu: 'Intel Iris Xe Graphics',
        battery: '51Wh',
        os: 'Windows 11',
        description: 'Laptop 2-in-1 với thiết kế xoay gập 360 độ và màn hình cảm ứng.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 34,
        name: 'Asus VivoBook Pro 16X',
        category: 'Laptop',
        brand: 'Asus',
        price: 37990000,
        oldPrice: 41990000,
        discount: 10,
        available: 9,
        quantity: 40,
        cpu: 'AMD Ryzen 9 6900HX',
        ram: '32GB',
        storage: '1TB SSD',
        screen: '16 inch, 4K OLED',
        gpu: 'NVIDIA GeForce RTX 3060',
        battery: '96Wh',
        os: 'Windows 11',
        description: 'Laptop dành cho sáng tạo nội dung với màn hình OLED 4K sắc nét.',
        image: '/images/laptop.jpeg',
    },
    {
        id: 35,
        name: 'Dell Inspiron 16 Plus',
        category: 'Laptop',
        brand: 'Dell',
        price: 28990000,
        oldPrice: 31990000,
        discount: 9,
        available: 10,
        quantity: 40,
        cpu: 'Intel Core i7-12700H',
        ram: '16GB',
        storage: '1TB SSD',
        screen: '16 inch, 3K',
        gpu: 'NVIDIA GeForce RTX 3050',
        battery: '86Wh',
        os: 'Windows 11',
        description: 'Laptop màn hình lớn với hiệu năng mạnh mẽ dành cho công việc và giải trí.',
        image: '/images/laptop.jpeg',
    },
];

export async function GET() {
    return new Response(JSON.stringify(products), { status: 200 });
}
